# essentials
hostname: jerry
username: similicious
public_domain: "{{ hostname }}"

# geerlingguy.security
security_ssh_port: 62748
security_sudoers_passwordless:
  - "{{ username }}"

# githubixx.ansible_role_wireguard
wireguard_address: "10.10.0.1/24"
wireguard_endpoint: "20.113.154.172"

# bertvv.samba
samba_users:
  - name: "{{ username }}"
    password: "{{ vault_samba_user_password }}"

samba_shares:
  - name: paperless-consume
    path: "{{ docker_service_conf_dir }}/paperless-ngx/consume"
    group: "{{ username }}"
    write_list: "{{ username }}"
  - name: photoprism-import
    path: "{{ docker_service_conf_dir }}/photoprism/import"
    group: "{{ username }}"
    write_list: "{{ username }}"
