---
- name: "Ensure the appdata directory for services exist"
  file:
    path: "{{ dawarich_compose_file | dirname }}"
    state: directory

- name: Ensure the docker-compose file is present
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ dawarich_compose_file }}"

- name: "Ensure the {{ service_name }} stack is running"
  community.docker.docker_compose_v2:
    project_name: "{{ service_name }}"
    project_src: "{{ dawarich_compose_file | dirname }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
