---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  similicious:
    disabled: false
    displayname: "Simon"
    password: "$argon2id$v=19$m=65536,t=3,p=4$qOFqm8ATMf0t0+FCh+bBuA$pq27a4Dqki4AaZnjKq0Wl7E+Aqbk4XQ+z5oDvoWbnqc" # yamllint disable-line rule:line-length
    email: mail@example.de
    groups:
      - admins
