---
- name: Setup home server
  hosts: morty
  become: true

  roles:
    - essentials
    - geerlingguy.security
    - geerlingguy.docker
    - bertvv.samba
    - traefik
    - portainer
    - authelia
    - stash
    - jellyfin
    - watchtower
