---
- name: Setup offsite nas
  hosts: offsitenas
  become: true

  roles:
    - role: geerlingguy.pip
      tags:
        - pip
    - role: geerlingguy.docker
      tags:
        - docker
    - role: uptime-kuma
      tags:
        - uptime-kuma
