---
- name: Setup RaspberryPi homeserver
  become: true
  hosts: raspberry

  roles:
    # - essentials
    # - geerlingguy.pip
    # - geerlingguy.docker_arm
    # - traefik
    # - portainer
    # - adguard-home
    # - homer
    # - mariadb
    # - uptime-kuma
    # - postgres
    # - tandoor-recipes
    # - monitoring
    - paperless-ngx
