---
roles:
  - name: geerlingguy.docker_arm
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: githubixx.ansible_role_wireguard
  - name: geerlingguy.security
  - name: geerlingguy.swap
  - name: geerlingguy.hdparm
collections:
  - name: community.docker
  - name: lucasheld.uptime_kuma
  - name: vladgh.samba
