---
roles:
  - name: geerlingguy.docker_arm
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: githubixx.ansible_role_wireguard
  - name: bertvv.samba
  - name: geerlingguy.security
collections:
  - name: community.docker
