---
- name: "Ensure {{ service_name }} is running as a container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    command: --interval 28800 --cleanup --no-startup-message
    env:
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: "generic+https://ntfy.sh/{{ vault_ntfy_topic }}?title=WatchtowerOn{{ hostname|title }}"
    restart_policy: unless-stopped
