---
- name: "Ensure exploit host repo is cloned and up to date"
  ansible.builtin.git:
    repo: "https://github.com/kmeps4/leeful900"
    dest: "{{ ps4_exploit_host_dir }}"

- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: nginx:alpine
    volumes:
      - "{{ ps4_exploit_host_dir }}:/usr/share/nginx/html:ro"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.ps4exploithost.rule: "Host(`ps4.{{ public_domain }}`) && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.ps4exploithost.loadbalancer.server.port: "80"
    networks:
      - name: "{{ traefik_network_name }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
