# geerlingguy.security
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "05:00"
security_autoupdate_mail_to: "{{ vault_autoupdate_mail_to }}"
security_autoupdate_mail_on_error: true

# Install the docker python sdk for ansible (community.docker)
pip_install_packages:
  - name: docker
  - name: docker-compose

# A list of system users to be added to the docker group
docker_users:
  - "{{ username }}"

# Path for docker containers to mount configs etc.
docker_service_conf_dir: "/home/{{ username }}/docker-services"
traefik_network_name: traefik

wireguard_unmanaged_peers:
  smartphone:
    public_key: jHqz4lrMWR04e/7GxA5EvrV20ztKuIeLAUnb00XkLgY=
    allowed_ips: 10.10.0.3/32
  laptop15:
    public_key: u7OuQmGFkZ43M7SU9J6nnv/x2Z6gNPJYeLuKwX8GJV0=
    allowed_ips: 10.10.0.4/32