# essentials
ssh_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqAobjlk5q1B5yHghi1hfCr9GSioXWKCNQtfsENN+azoZfLbtbx3B5BHEDW++QuVX5FuZXoX+osrRqLLYgYx7/5545PD8uAtcGhVYfQh3IOH2IEvyl3vxh7KwCnIS2T+Vol9VzKEtHidXTsEwdOt8Vl4CZ5Unl6/m3FVn0tpWNZkJ2dJs42WP/HkwItD0bpf/nhCLvCGYps5ZAeSHGdXXyBAt+9v6cZsPTmwlClfP+zBpg0G6rxKMVyEcU8KDQ0Rh6WtoM/9ROKPN3CiJkdGjohCZbztEh+BmlfLJirFIVSm4TIIfYp89CTSrongF7ImVUxtPcMfYUzwJxGg8Cl0+nhJnzGauSuqbtQi1WCzQu47dLayTB5c+ds0hU74IOm4pcEOPs6wl+CJwirRuzfFbDw34pjeV2puQ7Fctd4JRCig93RhHyKy4GmReQM+Eg9hfjW+dhORA7yr4zEBnMU/mw3gTzEYy7/j4KVH3tgd4V3ZPu2w1CXSMeAOKTl54aCUE= similicious@Morty
  - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGjJ9Vk617SZVr9Ou9HOZ4pavYHue1FyXj6szDmCVZLwPR5iJYGs06XHEwZhlTasEW8Xs6pQMm+mvw3Zz87yREf0wFoIZPzSnOXvGrGf0CMNCL6BbknqGSWDRpUvb6Sz9QNgyqK6keHs4fy+gY9m49ePsUTgUkhRDPB0fNwS4hV4Noobw== similicious@morty-ubuntu
  - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFk9F1J1YlHDzmKuh1pnzT/izO2WXtnbNi0obcb5QVmd2xwN8/kknX0roSkV9olFpkliSGJfLDUbldE5DddlKLaUQHQmfPds68uqRP0563dyk2vFIAdF2Bf5l5wAhX8hkdGtYXl+JpJa32KZbxLhrKIak+vFRxa7VxRFC09cuGuLtu/ZA== work
  - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABQ57mjgVd7QtaNd+YKg7vTzB1uHvqJvIx02chjLfHq4g8kwZJix6ZHEt2lFjjulhKRBR0CVEWHtxMsp+1LR82aowAfzNjkLAVXafpeIiSJrawExLv+jJAhEqwBA96xlIS567dRsLAHga5VRnpviuUyvmV+W+HiNokXRx7wgZ7opdP5WQ== JuiceSSH
  - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACNb0a4LTUo7AwXZvkj+LrPARrctb2+PYpBj/EhuI+U/SRSCGMFr0gGoc6En9jSfYQ+6pZirSD607LZeF5kIBzEyAHUXCDDSbe6OVYErxJ1Wq+yPPMnpXF5PZ49sXoJg0YAO0zXzMECgARGqXZLlqGr+DqoEtwUfNKzhlFkUM/RZmfL8g== similicious@Simons-iMac-Pro.local

# geerlingguy.security
security_autoupdate_reboot_time: "05:00"
security_autoupdate_mail_to: "{{ vault_autoupdate_mail_to }}"
security_autoupdate_mail_on_error: true

# geerlingguy.pip
# Install the docker python sdk for ansible (community.docker)
pip_install_packages:
  - name: docker
  - name: docker-compose

# traefik
traefik_internal_client_ip: "ClientIP(`10.10.0.0/16`, `192.168.178.0/24`, `127.0.0.1`, `::1`)"

# A list of system users to be added to the docker group
docker_users:
  - "{{ username }}"

docker_daemon_options:
  log-driver: "local"

# Path for docker containers to mount configs etc.
docker_service_conf_dir: "/home/{{ username }}/docker-services"

# traefik
traefik_network_name: traefik

# postgres
postgres_network_name: postgres

# githubixx.ansible_role_wireguard
wireguard_unmanaged_peers:
  smartphone:
    public_key: jHqz4lrMWR04e/7GxA5EvrV20ztKuIeLAUnb00XkLgY=
    allowed_ips: 10.10.0.3/32
  ipad:
    public_key: ZEzpus8c+2+UNO94LWTH+8a+l3zZdiqE+nztYDuBagQ=
    allowed_ips: 10.10.0.6/32
  thinkpad:
    public_key: UelAtkmNY1eTXFAYysV9oDHMXJmYlrFTaVlHOUFbAhE=
    allowed_ips: 10.10.0.4/32
  work:
    public_key: Gd60IXyqCxDjOXhylb4oMla6xFCtSFNXyMbCx7zGfkg=
    allowed_ips: 10.10.0.7/32
