# essentials
ssh_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqAobjlk5q1B5yHghi1hfCr9GSioXWKCNQtfsENN+azoZfLbtbx3B5BHEDW++QuVX5FuZXoX+osrRqLLYgYx7/5545PD8uAtcGhVYfQh3IOH2IEvyl3vxh7KwCnIS2T+Vol9VzKEtHidXTsEwdOt8Vl4CZ5Unl6/m3FVn0tpWNZkJ2dJs42WP/HkwItD0bpf/nhCLvCGYps5ZAeSHGdXXyBAt+9v6cZsPTmwlClfP+zBpg0G6rxKMVyEcU8KDQ0Rh6WtoM/9ROKPN3CiJkdGjohCZbztEh+BmlfLJirFIVSm4TIIfYp89CTSrongF7ImVUxtPcMfYUzwJxGg8Cl0+nhJnzGauSuqbtQi1WCzQu47dLayTB5c+ds0hU74IOm4pcEOPs6wl+CJwirRuzfFbDw34pjeV2puQ7Fctd4JRCig93RhHyKy4GmReQM+Eg9hfjW+dhORA7yr4zEBnMU/mw3gTzEYy7/j4KVH3tgd4V3ZPu2w1CXSMeAOKTl54aCUE= similicious@Morty
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDb+b1UEjR6qgjt5t8aMKdloIqF0UgRmCywSokFEMsdpKQlXuqcL5DHrr5llC2Csf7fumHRNBkiqbUbmLBvAR9nxBQU3LJgyjzvJTBasmK2QUBAwkgj+giKw4kDklpdQfJvqZoaBzi42cGucG9UigM09JCWr+qFXlBJaWr4e39yrxf/Xb7MReJwHdMRIZIoFg+5/zt4JCroKyLWxUscM8IgXBCHyGcPFyn0K0YzN4LbmG93opbiF19n42orhWru6Dwgg26Tz5HTbX/l7JSEBdap3jsKbdick2MNzmIiMqX9Ms7q6f6arFp5sdVbUB9yIk7TBIzloMZQzQ3zrAuFmmwbDemowfpDOKWFlOAjNprAuLmx7zl5Rb4g+pxG3YbGlZQMJLa7Ar021niTxT9H7u7cAilglUL+BDCGPuUByxqo3JVLRnrM3d1Pj75xaT1+TVaaiEOeD7WmPSNw8MvWezwzwwX6JZwlx32ZCCaIHvu80wvJH5AsoEEOW9qQn/O00b+46AklyhhDCG/gtqf4UvOQlLszXPPr65H/feAPKh79n3Nvr37UHahIw1qd+8qc+priZ6IMtPi1YCUsMBjGgn/1t9YUS7KcJX04fO7/CPYm5dHyxHkfezpP/Euqh6ZaCkI/etQZzKvSnWZkj3z0d11o0+bwryd23wPlymrVChUsRQ== similicious@WHITEPEGASUS
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTA3SAvSVpgmPpLvAiuHKhP7zJYDtMIdE2IVEBMpk3qB/BfrWOU3AtD1bUlk6IA2KSsmMPQxxkCfUHsOQgIb7SACnS46BpjOWwLe6WwW8QqHMOkyXjryryT1YezUFOWfvtQ0a2LBeoLcqjpibJsPozHxroD9vlK2MSJ5Ua+TZKJEnVOio4AwFe4XAdK1ycGdcsCMEjHLLFWDNzpjGSfPlPOf49H7ttG6SMSfHV+3WENSxayKnexJw4GxekwMWhQ+OoUYEDcUeFHpxwtCuHEXNdf0HNptNVQhpGcOKduo2atd21VTLPc/wBh1Qf5M/phJ3OaTWsGAJOFiNwQOLZ5vVB79J4PPzPJl8/d3oW3sHpzzHfT8QLr8/KIt/zzkQhEBMAqZ9H1XWz7HWajKym1x+AFyGj+n4XiDvXCRYB0kP4NrroDitnVWrawEYVZG568VRhSzIqSHi7utiCis50EDmowsOUGj79jhUnV1nzflhlS3G3NRpyP/Qxsy6lhCnObc8= similicious@MacBook-Pro.fritz.box

# geerlingguy.security
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "05:00"
security_autoupdate_mail_to: "{{ vault_autoupdate_mail_to }}"
security_autoupdate_mail_on_error: true

# Install the docker python sdk for ansible (community.docker)
pip_install_packages:
  - name: docker
  - name: docker-compose

# traefik
traefik_internal_client_ip: "ClientIP(`10.10.0.0/16`, `192.168.178.0/24`, `127.0.0.1`, `::1`)"

# A list of system users to be added to the docker group
docker_users:
  - "{{ username }}"

# Path for docker containers to mount configs etc.
docker_service_conf_dir: "/home/{{ username }}/docker-services"
traefik_network_name: traefik

wireguard_unmanaged_peers:
  smartphone:
    public_key: jHqz4lrMWR04e/7GxA5EvrV20ztKuIeLAUnb00XkLgY=
    allowed_ips: 10.10.0.3/32
  laptop15:
    public_key: u7OuQmGFkZ43M7SU9J6nnv/x2Z6gNPJYeLuKwX8GJV0=
    allowed_ips: 10.10.0.4/32