---
traefik_network_name: traefik
traefik_common_args: >
  --api.insecure=true
  --providers.docker
  --providers.docker.exposedByDefault=false
  --accesslog=true
  --entryPoints.http.address=:80
  --entryPoints.https.address=:443
  --entrypoints.https.http.tls=true