---
traefik_network_name: traefik

traefik_args:
traefik_args_default: >
  --api.dashboard=true
  --providers.docker=true
  --providers.docker.exposedByDefault=false
  --providers.file.filename=/etc/traefik/dynamic.yml
  --accesslog=true
  --entryPoints.http.address=:80
  --entryPoints.https.address=:443
  --entrypoints.https.http.tls=true
  --serverstransport.insecureskipverify=true
  --metrics.prometheus=true

# for debug logging, add the following to args:
#  --log.level=DEBUG

traefik_labels:
traefik_labels_default:
  # Expose traefik dashboard on subdomain
  traefik.enable: "true"
  traefik.http.routers.api.rule: "Host(`traefik.{{ public_domain }}`) && {{ traefik_internal_client_ip_v3 }}"
  traefik.http.routers.api.service: "api@internal"

traefik_env:

# Per default, a docker volume is used to store certs
traefik_ssl_certs_dir: "traefik_ssl_certs"

traefik_dynamic_file_path: "{{ docker_container_data_root }}/traefik/dynamic.yaml"
traefik_dynamic_file_dir: "{{ traefik_dynamic_file_path | dirname }}"
traefik_dynamic_file_content:
