---
- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: deluan/navidrome
    volumes:
      - "{{ navidrome_config_dir }}:/data"
      - "{{ navidrome_music_dir }}:/music"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.navidrome.rule: "Host(`navidrome.{{ public_domain }}`) && {{ traefik_internal_client_ip }}"
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"
      traefik.http.routers.navidrome.middlewares: "authelia@docker"
    env:
      ND_SPOTIFY_ID: "{{ vault_navidrome_spotify_client_id }}"
      ND_SPOTIFY_SECRET: "{{ vault_navidrome_spotify_client_secret }}"
      ND_LASTFM_APIKEY: "{{ vault_navidrome_lastfm_api_key }}"
      ND_LASTFM_SECRET: "{{ vault_navidrome_lastfm_shared_secret }}"
      ND_REVERSEPROXYWHITELIST: "172.18.0.0/16"
    networks:
      - name: "{{ traefik_network_name }}"
