---
- name: "Ensure {{ service_name }} is running as a container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: linuxserver/webtop:fedora-xfce
    security_opts:
      - "seccomp:unconfined"
    shm_size: "1GB"
    restart_policy: unless-stopped
    volumes:
      - "{{ storage_media_dir }}:/mnt/media"
      - "{{ storage_data_dir }}:/mnt/data"
      - "{{ webtop_dir }}:/config"
    networks:
      - name: "{{ traefik_network_name }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.webtop.rule: "Host(`webtop.{{ public_domain }}`)  && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.webtop.loadbalancer.server.port: "3000"
      traefik.http.routers.webtop.middlewares: "authelia@docker"
      traefik.http.middlewares.webtoplossless.headers.customResponseHeaders.Cross-Origin-Embedder-Policy: "require-corp"
      traefik.http.middlewares.webtoplossless.headers.customResponseHeaders.Cross-Origin-Opener-Policy: "same-origin"
      traefik.http.middlewares.webtoplossless.headers.customResponseHeaders.Cross-Origin-Resource-Policy: "same-site"
      com.centurylinklabs.watchtower.enable: "false"
    env:
      TZ: Europe/Berlin
      PUID: "{{ docker_container_puid | string }}"
      PGID: "{{ docker_container_pgid | string }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
