---
- name: "Ensure the appdata directory for services exist"
  file:
    path: "{{ nextcloud_compose_file | dirname }}"
    state: directory

- name: Ensure the docker-compose file is present
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ nextcloud_compose_file }}"

- name: "Make sure {{ service_name }} is running as a container"
  community.docker.docker_compose_v2:
    project_name: "{{ service_name }}"
    project_src: "{{ nextcloud_compose_file | dirname }}"
