---
service_name: filebrowser

filebrowser_puid: 1000
filebrowser_pgid: 1000

filebrowser_mounts:
filebrowser_mounts_default:
  - /var/run/docker.sock:/var/run/docker.sock
  - "{{ docker_container_data_root }}/{{ service_name }}/database:/database"
  - "{{ docker_container_data_root }}/{{ service_name }}/settings.json:/config/settings.json"
