---
identity_validation:
  reset_password:
    jwt_secret: "{{ vault_authelia_identity_validation_reset_password_jwt_secret }}"

server:
  address: "0.0.0.0:9091"

log:
  level: info

totp:
  issuer: "{{ public_domain }}"

# authentication_backend:
#   file:
#     path: /config/users_database.yml

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    base_dn: "{{ vault_lldap_base_dn }}"
    user: "uid=authelia,ou=people,{{ vault_lldap_base_dn }}"
    password: "{{ vault_authelia_authentication_backend_ldap_password }}"

access_control:
  default_policy: deny
  rules:
    - domain: "sabnzbd.{{ public_domain }}"
      policy: bypass
      resources:
        - "^/sabnzbd/api"
    - domain: "navidrome.{{ public_domain }}"
      policy: bypass
      resources:
        - "^/rest"
    - domain: "stash.{{ public_domain }}"
      policy: bypass
      resources:
        - '^\/scene\/\d+\/screenshot\?t=\d+'
        - '^\/scene\/\d+\/stream'
    - domain: "*.{{ public_domain }}"
      subject: "group:admin"
      policy: two_factor

session:
  secret: "{{ vault_authelia_session_secret }}"
  name: authelia_session

  cookies:
    - domain: "{{ public_domain }}"
      authelia_url: "https://auth.{{ public_domain }}"
      name: "authelia_session"

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: "{{ vault_authelia_storage_encryption_key }}"
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  smtp:
    address: "submissions://smtp.mailbox.org:465"
    username: "{{ vault_authelia_notifier_smtp_username }}"
    password: "{{ vault_authelia_notifier_smtp_password }}"
    sender: "{{ public_domain }} Account <no-reply@{{ public_domain }}>"
    subject: "[{{ public_domain }}] {title}"
    startup_check_address: "no-reply@{{ public_domain }}"

identity_providers:
  oidc:
    hmac_secret: "{{ vault_authelia_identity_providers_oidc_hmac_secret }}"
    authorization_policies:
      admin:
        default_policy: "deny"
        rules:
          - policy: "two_factor"
            subject: "group:admin"
      home:
        default_policy: "deny"
        rules:
          - policy: "one_factor"
            subject: "group:home"
      media:
        default_policy: "deny"
        rules:
          - policy: "one_factor"
            subject: "group:media"
    jwks:
      - algorithm: "RS256"
        certificate_chain: |
          {{ vault_authelia_identity_providers_oidc_jwks_0_certificate_chain | indent(10) }}
        key: |
          {{ vault_authelia_identity_providers_oidc_jwks_0_key | indent(10) }}
    clients:
      - client_id: WfPwIhhhiysG8kWq87mjxspmWBIqs7QdZ2jlVamHyK-ZNEhgQfD9NLZ21KXL5Egjpx7YfV1L
        client_name: Portainer
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_portainer_client_secret_hash }}"
        redirect_uris:
          - "https://portainer.{{ public_domain }}"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        token_endpoint_auth_method: client_secret_post
        authorization_policy: "admin"
      - client_id: "3AWTOoPVAb1pCCuWsm_LVneQXjLLpoy9DUwB1LRNrk2y2bqGao_Yels~RbDbYcLI90oQrc2U"
        client_name: "Vikunja"
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_vikunja_client_secret_hash }}"
        redirect_uris:
          - "https://vikunja.{{ public_domain }}/auth/openid/"
          - "https://vikunja.{{ public_domain }}/auth/openid/authelia"
          - "https://vikunja.{{ public_domain }}/api/oidc/authorization"
        scopes:
          - "openid"
          - "email"
          - "profile"
        token_endpoint_auth_method: "client_secret_post"
        authorization_policy: "admin"
      - client_id: "UfBkDkVyVdJ2a4CLi4P7KmGb3y-szYhMSuorqJzj2Z74d6PJ2Mp503yGIP4Nw._Z-98RVrJ-"
        client_name: "Proxmox"
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_proxmox_client_secret_hash }}"
        require_pkce: true
        pkce_challenge_method: "S256"
        redirect_uris:
          - "https://proxmox.{{ public_domain }}"
        scopes:
          - "openid"
          - "profile"
          - "email"
        authorization_policy: "admin"
      - client_id: "yJWTAHtl5HUGWiTJWSWqTxGkTskmvRMq.moBTLfdRjImu9hZi_ZQxXK.QIJ~2_SMx00Eoivf"
        client_name: "Beszel"
        client_secret: "$pbkdf2-sha512$310000$n4XbLwDHEqbjrxGQQ267/w$YH5e5nPKmRVnIiQ5r6kiDSWXhLzzcC.f8K4bPuwb91IpEj4cSAQxtZjqPnfYc7blP9Fr36U5qj1c4MMcHqvLYg"
        public: false
        redirect_uris:
          - "https://beszel.{{ public_domain }}/api/oauth2-redirect"
        scopes:
          - "email"
          - "groups"
          - "openid"
          - "profile"
        userinfo_signed_response_alg: "none"
        authorization_policy: "admin"
      - client_id: "IoJ~hP3w4Y9AnVRCfWvGDoC48djIzBf9JBSw30LdrgsUaGVUy.9o4bwACXtbzmx.DMhu9w1w"
        client_name: "Open WebUI"
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_openwebui_client_secret_hash }}"
        public: false
        redirect_uris:
          - "https://ai.{{ public_domain }}/oauth/oidc/callback"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        userinfo_signed_response_alg: "RS256"
        authorization_policy: "admin"
      - client_id: "nNlYOuyXIo~EcxPabcIF.hRwhUJ-2qKnxhf~ozScnprpGFY"
        client_name: KitchenOwl
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_kitchenowl_client_secret_hash }}"
        public: false
        authorization_policy: home
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://kitchenowl.{{ public_domain }}/signin/redirect
          - kitchenowl:///signin/redirect
        response_modes: []
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post
      - client_id: "sQmSPlNkZ4x~qxgaYB85nWCD.NP33em50WexTg23sdf"
        client_name: Audiobookshelf
        client_secret: "{{ vault_authelia_identity_providers_oidc_clients_audiobookshelf_client_secret_hash }}"
        redirect_uris:
          - "https://audiobookshelf.{{ public_domain }}/audiobookshelf/auth/openid/callback"
          - "https://audiobookshelf.{{ public_domain }}/audiobookshelf/auth/openid/mobile-redirect"
          - "audiobookshelf://oauth"
          - "plappa://oauth"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        authorization_policy: "media"
