---
identity_validation:
  reset_password:
    jwt_secret: "{{ vault_authelia_jwt_secret }}"

server:
  address: "0.0.0.0:9091"

log:
  level: info

totp:
  issuer: "{{ public_domain }}"

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  rules:
    - domain: "sabnzbd.{{ public_domain }}"
      policy: bypass
      resources:
        - "^/sabnzbd/api"
    - domain: "navidrome.{{ public_domain }}"
      policy: bypass
      resources:
        - "^/rest"
    - domain: "stash.{{ public_domain }}"
      policy: bypass
      resources:
        - '^\/scene\/\d+\/screenshot\?t=\d+'
        - '^\/scene\/\d+\/stream'

session:
  secret: "{{ vault_authelia_session_secret }}"
  name: authelia_session

  cookies:
    - domain: "{{ public_domain }}"
      authelia_url: "https://auth.{{ public_domain }}"
      name: "authelia_session"

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: i3M8CoSKw2axy9Q7GL74jTHCu3yY5XdKDJLrmxSxM5YDwE6qs5z8k7qTCmzLD4zx
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
# identity_providers:
#   oidc:
#     hmac_secret:
#     issuer_certificate_chain:
#     issuer_private_key:
#     access_token_lifespan: 1h
#     authorize_code_lifespan: 1m
#     id_token_lifespan: 1h
#     refresh_token_lifespan: 90m
#     enable_client_debug_messages: false
#     enforce_pkce: public_clients_only
#     clients:
#       - id: grafana
#         description: Grafana
#         secret: "$argon2id$v=19$m=65536,t=3,p=4$l19OIyaEZjwj1MQfMSJqyA$4oN554Y96IVyXPJxNz9hDZ/+hUb3i1XAMZfzcwePovU"
#         public: false
#         authorization_policy: two_factor
#         redirect_uris:
#           - "https://grafana.{{ public_domain }}/login/generic_oauth"
#         scopes:
#           - openid
#           - profile
#           - groups
#           - email
#         userinfo_signing_algorithm: none
