---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  similicious:
    disabled: false
    displayname: "Simon"
    password: "$argon2id$v=19$m=65536,t=3,p=4$IGN71rtyt4sVcdQ58WVUKQ$hgV24OnttTc76dWQPWVbChoAc4dMGOW32ckr/3OPc4s" # yamllint disable-line rule:line-length
    email: "{{ vault_mail }}"
    groups:
      - admins
