---
- name: Ensure the config directory exists
  file:
    path: "{{ docker_service_conf_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Ensure the config subfolder for recipes exists"
  file:
    path: "{{ docker_service_conf_dir }}/recipes"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Ensure the environment file exists"
  template:
    src: .env.j2
    dest: "{{ docker_service_conf_dir }}/recipes/.env"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensure the tandoor-recipes stack is running
  docker_compose:
    project_name: recipes
    definition:
      version: "3"
      services:

        db:
          container_name: recipes-db
          image: postgres:11-alpine
          ports:
            - 5432:5432
          volumes:
            - recipes-db_data:/var/lib/postgresql/data
          env_file:
            - "{{ docker_service_conf_dir }}/recipes/.env"
          networks:
            - app
          restart: always
          logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"

        app:
          container_name: recipes-app
          image: vabene1111/recipes
          env_file:
            - "{{ docker_service_conf_dir }}/recipes/.env"
          volumes:
            - "recipes_staticfiles:/opt/recipes/staticfiles"
            - "recipes_nginx_config:/opt/recipes/nginx/conf.d"
            - "{{ docker_service_conf_dir }}/recipes/mediafiles:/opt/recipes/mediafiles"
          depends_on:
            - db
          networks:
            - app
          logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"

        web:
          container_name: recipes-web
          image: nginx:mainline-alpine
          restart: always
          env_file:
            - "{{ docker_service_conf_dir }}/recipes/.env"
          volumes:
            - "recipes_staticfiles:/static"
            - "recipes_nginx_config:/etc/nginx/conf.d:ro"
            - "{{ docker_service_conf_dir }}/recipes/mediafiles:/media"
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.recipes.rule=Host(`recipes.{{ hostname }}`)"
            - "traefik.docker.network={{ traefik_network_name }}"
          depends_on:
            - app
          links:
            - "app:web_recipes"
          networks:
            - app
            - "{{ traefik_network_name }}"
          logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"

      volumes:
        recipes-db_data:
        recipes_staticfiles:
        recipes_nginx_config:

      networks:
        app:
        traefik:
          external: true