---
- name: "Ensure the appdata directory for services exist"
  file:
    path: "{{ recipes_compose_dir }}"
    state: directory

- name: Ensure the docker-compose file is present
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ recipes_compose_file }}"

- name: "Ensure the environment file exists"
  template:
    src: .env.j2
    dest: "{{ recipes_compose_dir }}/.env"

- name: "Ensure the {{ service_name }} stack is running"
  community.docker.docker_compose_v2:
    project_name: "{{ service_name }}"
    project_src: "{{ recipes_compose_dir }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
