---
- name: "Ensure the appdata directory for services exist"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ scrutiny_dir }}"
    - "{{ scrutiny_config_dir }}"
    - "{{ scrutiny_db_dir }}"

- name: "Ensure the configuration for {{ service_name }} is in place"
  ansible.builtin.template:
    src: "scrutiny.yaml.j2"
    dest: "{{ scrutiny_config_dir }}/scrutiny.yaml"
  notify: restart_scrutiny

- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    hostname: "{{ hostname }}"
    name: "{{ service_name }}"
    image: ghcr.io/analogj/scrutiny:master-omnibus
    volumes:
      - "{{ scrutiny_config_dir }}:/opt/scrutiny/config"
      - "{{ scrutiny_db_dir }}:/opt/scrutiny/influxdbsh"
      - /run/udev:/run/udev:ro
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.scrutiny.rule: "Host(`scrutiny.{{ public_domain }}`)  && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.scrutiny.loadbalancer.server.port: "8080"
    devices:
      - /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_D7GUAKLN:/dev/sda
      - /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_D7GUH0TN:/dev/sdb
      - /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_D7GY9YAN:/dev/sdc
      - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNX0W559138B:/dev/sde
    capabilities:
      - SYS_RAWIO
      - SYS_ADMIN
    networks:
      - name: "{{ traefik_network_name }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
