---
- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: ghcr.io/actualbudget/actual-server:latest
    volumes:
      - "{{ actual_dir }}:/data"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.actual.rule: "Host(`actual.{{ public_domain }}`) && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.actual.loadbalancer.server.port: "5006"
    networks:
      - name: "{{ traefik_network_name }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
