---
- name: "Ensure the appdata directory for {{ service_name }} exist"
  file:
    path: "{{ authelia_config_dir }}"
    state: directory

- name: "Ensure the compose directory for {{ service_name }} exist"
  file:
    path: "{{ authelia_compose_dir }}"
    state: directory

- name: Ensure the docker-compose file is present
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ authelia_compose_file }}"

- name: "Ensure the configuration for {{ service_name }} is in place"
  ansible.builtin.template:
    src: "configuration.yml"
    dest: "{{ authelia_config_dir }}/configuration.yml"
  notify: restart_authelia

- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_compose_v2:
    project_name: "{{ service_name }}"
    project_src: "{{ authelia_compose_dir }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
