---
- name: restart_telegraf
  community.docker.docker_container:
    name: telegraf
    state: started
    restart: true
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"

- name: restart_prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
