---
- name: restart_telegraf
  community.docker.docker_container:
    name: telegraf
    state: started
    restart: true

- name: restart_prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true
