---
- name: "Ensure portainer is running as a docker container"
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart_policy: always
    log_driver: json-file
    log_options:
      max-size: "200k"
      max-file: "10"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_subdomain }}.{{ public_domain }}`) && {{ traefik_internal_client_ip }}"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
    networks:
      - name: "{{ traefik_network_name }}"
