---
- name: "Ensure the folder structure for {{ service_name }} exists"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_container_puid | int }}"
    group: "{{ docker_container_pgid | int }}"
  with_items:
    - "{{ adguard_config_dir }}"
    - "{{ adguard_config_dir }}/conf"
    - "{{ adguard_config_dir }}/work"

- name: "Ensure the config for {{ service_name }} is present"
  template:
    src: AdGuardHome.yaml.j2
    dest: "{{ adguard_config_dir }}/conf/AdGuardHome.yaml"
    owner: "{{ docker_container_puid | int }}"
    group: "{{ docker_container_pgid | int }}"
  notify: restart_adguard

- name: Ensure adguard-home docker image is downloaded
  docker_image:
    name: adguard/adguardhome
    source: pull

# Not required on proxmox
# - import_tasks: ./deactivate-dnsstublistener.yml

- name: Ensure adguard-home is running as a docker container
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - "{{ adguard_config_dir }}/work:/opt/adguardhome/work"
      - "{{ adguard_config_dir }}/conf:/opt/adguardhome/conf"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.rule: "Host(`adguard.{{ public_domain }}`) && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.adguard.loadbalancer.server.port: "80"
    networks:
      - name: "{{ traefik_network_name }}"
    healthcheck:
      # Workaround for https://github.com/AdguardTeam/AdGuardHome/issues/5714
      test: ["NONE"]
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
