---
- name: "Ensure the config subfolder for {{ service_name }} exists"
  file:
    path: "{{ jellystat_dir }}"
    state: directory
    owner: "{{ docker_container_puid | int }}"
    group: "{{ docker_container_pgid | int }}"

- name: "Ensure the {{ service_name }} stack is running"
  docker_compose:
    project_name: "{{ service_name }}"
    definition:
      version: "3"
      services:
        jellystat-db:
          container_name: jellystat-db
          image: postgres:15.2
          environment:
            POSTGRES_DB: "jfstat"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
          volumes:
            - "{{ jellystat_db_dir }}:/var/lib/postgresql/data"
          networks:
            - app

        jellystat-app:
          container_name: jellystat-app
          image: cyfershepard/jellystat:latest
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
            POSTGRES_IP: jellystat-db
            POSTGRES_PORT: 5432
            JWT_SECRET: "my-secret-jwt-key"
          volumes:
            - "{{ jellystat_app_dir }}:/app/backend/backup-data"
          labels:
            traefik.enable: "true"
            traefik.http.routers.jellystat.rule: "Host(`jellystat.{{ public_domain }}`) && {{ traefik_internal_client_ip }}"
            traefik.http.routers.jellystat.middlewares: "authelia@docker"
            traefik.http.services.jellystat.loadbalancer.server.port: "3000"
            traefik.docker.network: "{{ traefik_network_name }}"
          networks:
            - app
            - "{{ traefik_network_name }}"
          depends_on:
            - jellystat-db

      networks:
        app:
        traefik:
          external: true
