---
- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    hostname: "{{ service_name }}"
    name: "{{ service_name }}"
    image: stashapp/stash:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ stash_config_dir }}:/root/.stash"
      - "{{ stash_media_dir }}:/data"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.stash.rule: "Host(`stash.{{ public_domain }}`)"
      traefik.http.services.stash.loadbalancer.server.port: "9999"
      traefik.http.routers.stash.middlewares: "authelia@docker"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    networks:
      - name: "{{ traefik_network_name }}"
