services:
  changedetection:
    container_name: "{{ service_name }}"
    image: ghcr.io/dgtlmoon/changedetection.io
    hostname: "{{ service_name }}"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.changedetection.rule: "Host(`changedetection.{{ public_domain }}`) && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.changedetection.loadbalancer.server.port: "5000"
      traefik.docker.network: "{{ traefik_network_name }}"
      traefik.http.routers.changedetection.middlewares: "authelia@docker"
    networks:
      - "{{ traefik_network_name }}"
      - app
    environment:
      BASE_URL: "https://changedetection.{{ public_domain }}"
      LOGGER_LEVEL: info
      TZ: "Europe/Berlin"
      PLAYWRIGHT_DRIVER_URL: "ws://browser-sockpuppet-chrome:3000"
    volumes:
      - "{{ changedetection_dir }}:/datastore"
    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started

  browser-sockpuppet-chrome:
    hostname: browser-sockpuppet-chrome
    container_name: "{{ service_name }}-chrome"
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      - app

networks:
  app:
  traefik:
    external: true
