---
- name: Ensure the proxy network exists
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"

- name: Ensure Traefik is running as a container
  community.docker.docker_container:
    name: traefik
    image: traefik:2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ traefik_ssl_certs_dir }}:/ssl-certs"
    command: >
      {{ traefik_args_default }}
      {{ traefik_args }}
    networks:
      - name: "{{ traefik_network_name }}"
        ipv4_address: "172.18.0.4"
    labels: "{{ traefik_labels_default | combine(traefik_labels) }}"
    env: "{{ traefik_env }}"
    restart_policy: unless-stopped
