---
- name: Ensure the proxy network exists
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"

- name: Ensure Traefik is running as a container
  community.docker.docker_container:
    name: traefik
    image: traefik:2.9
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_ssl_certs:/ssl-certs
    command: >
      {{ traefik_common_args }}
      {{ traefik_args }}
    networks:
      - name: "{{ traefik_network_name }}"
    labels: "{{ traefik_labels }}"
    env:
      HETZNER_API_KEY: "{{ vault_hetzner_api_key }}"
    restart_policy: always
    log_driver: json-file
    log_options:
      max-size: "200k"
      max-file: "10"
