---
- name: Ensure uptime-kuma is running as a container
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    volumes:
      - "uptime-kuma_data:/app/data"
    restart_policy: always
    log_driver: json-file
    log_options:
      max-size: "200k"
      max-file: "10"
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime.rule: "Host(`{{ uptime_kuma_http_subdomain}}.{{ rpi_hostname }}`)"
    networks:
      - name: "{{ traefik_network_name }}"