---
- name: "Ensure {{ service_name }} is running as a container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    restart_policy: unless-stopped
    image: louislam/uptime-kuma
    volumes:
      - "{{ uptime_kuma_data_dir }}:/app/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime.rule: "Host(`uptime.{{ public_domain }}`) && {{ traefik_internal_client_ip }}"
    networks:
      - name: "{{ traefik_network_name }}"
