# vars
storage_dir: "/mnt/storage"
storage_media_dir: "{{ storage_dir }}/media"
storage_data_dir: "{{ storage_dir }}/data"

# essentials
hostname: bloom
public_domain: "{{ vault_public_domain }}"
username: ubuntu

# geerlingguy.security
security_sudoers_passwordless:
  - "{{ username }}"

security_ssh_allowed_users:
  - "{{ username }}"

# all docker services
docker_container_data_root: "/docker/data"
docker_container_puid: 1000
docker_container_pgid: 1000

# role: traefik
traefik_ssl_certs_dir: "{{ docker_container_data_root }}/traefik/certificates"
traefik_args: >
  --entrypoints.http.http.redirections.entryPoint.to=https
  --entrypoints.http.http.redirections.entryPoint.scheme=https
  --entrypoints.http.http.redirections.entrypoint.permanent=true
  --entrypoints.https.http.tls.certResolver=letsencrypt
  --entrypoints.https.http.tls.domains[0].main={{ public_domain }}
  --entrypoints.https.http.tls.domains[0].sans=*.{{ public_domain }}
  --certificatesresolvers.letsencrypt.acme.email={{ vault_email }}
  --certificatesresolvers.letsencrypt.acme.dnschallenge=true
  --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=193.47.99.5:53,213.133.100.98:53
  --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=10
  --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=hetzner
  --certificatesresolvers.letsencrypt.acme.storage=/ssl-certs/acme.json
traefik_env:
  HETZNER_API_KEY: "{{ vault_hetzner_api_key }}"
traefik_labels:
  traefik.enable: "false"

# role: portainer
portainer_config_dir: "{{ docker_container_data_root }}/portainer"
