services:
  app:
    container_name: "{{ service_name }}-app"
    image: vabene1111/recipes
    restart: unless-stopped
    env_file:
      - "{{ recipes_compose_dir }}/.env"
    volumes:
      - "{{ recipes_app_staticfiles_dir }}:/opt/recipes/staticfiles"
      - "{{ recipes_app_media_dir }}:/opt/recipes/mediafiles"
    networks:
      - app
      - "{{ traefik_network_name }}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.rule=Host(`{{ service_name }}.{{ public_domain }}`)"
      - "traefik.docker.network={{ traefik_network_name }}"

  db:
    container_name: "{{ service_name }}-db"
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - "{{ recipes_db_dir }}:/var/lib/postgresql/data"
    env_file:
      - "{{ recipes_compose_dir }}/.env"
    networks:
      - app

networks:
  app:
  traefik:
    external: true
