---
- name: "Ensure the hostname is set to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: "Ensure passwordless sudo is enabled for user {{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Ensure all packages are updated to their latest version
  apt:
    update_cache: yes
    upgrade: yes

- name: Ensure essential packages are installed
  package:
    name: "{{ essential_packages }}"
    state: present
