---
- name: "Ensure the hostname is set to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: "Ensure the user {{ username }} exists and is in sudo group"
  user:
    name: "{{ username }}"
    group: sudo
    shell: /bin/bash

- name: "Ensure the public key is authorized to login as {{ username }}"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/similicious/.ssh/id_rsa.pub') }}"

- name: Ensure all packages are updated to their latest version
  apt:
    update_cache: yes
    upgrade: yes

- name: Ensure essential packages are installed
  package:
    name: "{{ essential_packages }}"
    state: present
