---
- name: "Ensure the hostname is set to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: "Ensure the group {{ username }} exists and its id is 1000"
  group:
    name: "{{ username }}"
    state: "present"
    gid: 1000

- name: "Ensure the user {{ username }} exists and is in sudo group"
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    groups:
      - sudo
    append: true
    shell: /bin/bash

- name: "Ensure my public keys are authorized to login as {{ username }}"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: Ensure all packages are updated to their latest version
  apt:
    update_cache: yes
    upgrade: yes

- name: Ensure essential packages are installed
  package:
    name: "{{ essential_packages }}"
    state: present
