---
- name: "Ensure {{ service_name }} is running as a docker container"
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: ghcr.io/similicious/hibiscus-server-docker:2.10.24
    volumes:
      - "{{ hibiscus_server_dir }}:/opt/hibiscus-data"
    restart_policy: unless-stopped
    env:
      HIBISCUS_PASSWORD: "{{ vault_hibiscus_server_master_password }}"
      PUID: "{{ docker_container_puid | string }}"
      PGID: "{{ docker_container_pgid | string }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.hibiscus.rule: "Host(`hibiscus.{{ public_domain }}`)  && {{ traefik_internal_client_ip_v3 }}"
      traefik.http.services.hibiscus.loadbalancer.server.port: "8080"
      traefik.http.services.hibiscus.loadbalancer.server.scheme: "https"
    networks:
      - name: "{{ traefik_network_name }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
